import re

ORACLE_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
ORACLE_CACHE_TIMESTAMP_FIELD = "ADDED_AT"
ORACLE_VECTOR_INDEX_TYPES = ("HNSW", "IVF")
ORACLE_VECTOR_DISTANCE_METRICS = (
    "EUCLIDEAN",
    "EUCLIDEAN_SQUARED",
    "L2_SQUARED",
    "COSINE",
    "DOT",
    "MANHATTAN",
    "HAMMING",
    "JACCARD",
)
ORACLE_VECTOR_INDEX_ORGANIZATIONS = {
    "HNSW": "INMEMORY NEIGHBOR GRAPH",
    "IVF": "NEIGHBOR PARTITIONS",
}

ORACLE_RAW_PAYLOAD_FIELD = "RAW_PAYLOAD"
ORACLE_SOURCE_URL_FIELD = "SOURCE_URL"
ORACLE_SOURCE_TITLE_FIELD = "SOURCE_TITLE"
ORACLE_RETRIEVAL_QUERY_FIELD = "RETRIEVAL_QUERY"
ORACLE_RETRIEVAL_TIMESTAMP_FIELD = "RETRIEVAL_TIMESTAMP"
ORACLE_RETRIEVAL_MODE_FIELD = "RETRIEVAL_MODE"
ORACLE_CACHE_HIT_FIELD = "CACHE_HIT"
ORACLE_INSERTED_FROM_FIELD = "INSERTED_FROM"
ORACLE_PROVIDER_NAME_FIELD = "PROVIDER_NAME"
